# Generated by Django 5.0.2 on 2024-02-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_videos_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videos',
            new_name='VideosDb',
        ),
    ]
