# Generated by Django 5.0.2 on 2024-03-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_progressdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressDb',
        ),
    ]
