# Generated by Django 5.0.2 on 2024-03-23 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_progressdb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watched', models.BooleanField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.videosdb')),
            ],
        ),
    ]
